### ISSUE TITLE
 Wallpaper switcher doesn't display text on OpenSUSE

### ISSUE THREAD

**Issue by TNTRedstone** [CoolerWuffi/hyprland-dotfiles#19]
I have 2 computers using your rofi wallpaper selector, one on Arch btw and another on OpenSUSE Tumbleweed. On my Arch computer it works perfectly. However on my main OpenSUSE desktop it has no text and as a result no marking on the selected wallpaper

Arch:
![20240225_18h42m07s_grim](https://github.com/develcooking/hyprland-dotfiles/assets/73077470/1cfc20ef-0010-4ab9-9463-66dadaadda14)

OpenSUSE:
![20240225_18h43m59s_grim](https://github.com/develcooking/hyprland-dotfiles/assets/73077470/95917dba-db6b-4e8c-9d69-e061cecdb407)

**Comment by TNTRedstone** [comment]
Just discovered the problem: Arch's verion is `1.7.5+wayland2` while OpenSUSE's version is `1.7.5+wayland2-dev` Gonna build from source tommorow

**Comment by develcooking** [comment]
It's probably a downstream issue on OpenSuse. I'm looking forward to hear from you.

**Comment by TNTRedstone** [comment]
yeah fixed it by using a nix package instead but caused a locale problem so now I need an env variable to launch rofi lol
